# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RxSwiftExample1' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for RxSwiftExample1
	pod 'RxSwift'
	pod 'RxCocoa'
  target 'RxSwiftExample1Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'RxSwiftExample1UITests' do
    # Pods for testing
  end

end
